# Generated by Django 2.2.7 on 2022-11-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('collection', models.CharField(choices=[('SU', 'Summer'), ('FL', 'Fall'), ('SP', 'Spring'), ('WN', 'Winter')], max_length=2)),
                ('description', models.TextField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
